### ISSUE TITLE
Websocket server at api.tibber.com has been switched off as scheduled for December 2022

### ISSUE THREAD

**Issue by sindredahlen** [turbosnute/tibberpulse-influxdb#1]
Hey :)

I have been using your work for some time now, and since mid-december it stopped logging data to InfluxDB.
At Tibbers website they have an announcement that they discontinued the websocket server api.tibber.com.
https://5yq2fhgh0sfy.statuspage.io/incidents/fkh9ml637jf1

Is this the end of beatuiful Grafana dashboards, or can it be fixed?

FYI: The TibberInfo-influxDB still works :)

```
### Logfile output:
Sat Jan 7 10:59:03 UTC 2023
--- Start Call API
--- request header ---
GET /v1-beta/gql/subscriptions HTTP/1.1
Upgrade: websocket
Host: api.tibber.com
Origin: http://api.tibber.com
Sec-WebSocket-Key: ###################
Sec-WebSocket-Version: 13

Connection: upgrade
Sec-WebSocket-Protocol: graphql-subscriptions


-----------------------
--- response header ---
HTTP/1.1 404 Not Found
Server: awselb/2.0
Date: Sat, 07 Jan 2023 10:59:04 GMT
Content-Length: 90
Connection: keep-alive
Content-Type: text/plain
-----------------------
Using homeid '#######################' 
Handshake status 404 Not Found
### closed ###
Sat Jan 7 10:59:04 UTC 2023
```

**Comment by turbosnute** [comment]
I'll take a look!

**Comment by turbosnute** [comment]
@sindredahlen  I think I have fixed it now, can you test?

**Comment by sindredahlen** [comment]
@turbosnute Thanks for looking into this !

> @sindredahlen I think I have fixed it now, can you test?

I've started a new container, per instructions. 
Logfile:
docker: error during connect: Post "http://docker:2375/v1.24/containers/create?name=tibberpulse-influxdb": dial tcp: lookup docker on 192.168.2.1:53: no such host.

See 'docker run --help'.

We can continue testing via e-mail or discord or something to keep this thread clean, if you wish.


##########Update#############

I started a new container with a different name, and now the logfile is back to what it was originally:

```
Thu Jan 12 11:22:47 UTC 2023
--- Start Call API
--- request header ---
GET /v1-beta/gql/subscriptions HTTP/1.1
Upgrade: websocket
Host: api.tibber.com
Origin: http://api.tibber.com
Sec-WebSocket-Key: ##############
Sec-WebSocket-Version: 13

Connection: upgrade
Sec-WebSocket-Protocol: graphql-subscriptions


-----------------------
--- response header ---
HTTP/1.1 404 Not Found
Server: awselb/2.0
Date: Thu, 12 Jan 2023 11:22:47 GMT
Content-Length: 90
Connection: keep-alive
Content-Type: text/plain
-----------------------
Using homeid ############ (Rognstadvegen 45)
Handshake status 404 Not Found
### closed ###
Thu Jan 12 11:22:47 UTC 2023
Sleep 60
```

**Comment by turbosnute** [comment]
@sindredahlen You can contact me at discord Turbosnute#9514 or email oyvind.nilsen@gmail.com.

Does it work now? I see there is a 404 error?

In that case, it might be a db connection issue. Are you sure that you specified all the environment variables (especially INFLUXDB_HOST) and that this container is connected to the same network as your influxdb container.

**Comment by sindredahlen** [comment]
Thank you so much for sorting this out!
Everything is back in working order after your last update.
